title: Bay Area Municipal Codes
description: List of habitability related codes for various Bay Area municipalities
show_downloads: false

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme